TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN"
ADMIN_USER_IDS = [123456789]  # Replace with actual admin Telegram IDs
GOOGLE_DRIVE_FOLDER_ID = "YOUR_DRIVE_FOLDER_ID"
GOOGLE_CREDENTIALS_JSON = "credentials.json"
DELETE_COMMANDS_AFTER = 30  # Seconds
DELETE_FILES_AFTER = 900   # Seconds (15 min)
