services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8186227901:AAH9MU07NdnAUFiywAIMpxHitA5V3O1b3hw
      - key: ADMIN_IDS
        value: 5558589142
      - key: GOFILE_TOKEN
        value: 7MaibQTxRi8BN0zKD8NDoCwXDABdA8Jq
      - key: WEBHOOK_DOMAIN
        value: https://fastdl4u.onrender.com
