services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8186227901:AAH9MU07NdnAUFiywAIMpxHitA5V3O1b3hw
      - key: GOFILE_TOKEN
        value: 7MaibQTxRi8BN0zKD8NDoCwXDABdA8Jq
